name: generate animation

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allows to manually run the job at any time
  workflow_dispatch:

  # Run on every push on the main branch
  push:
    branches:
      - main

jobs:
  generate:
    name: Jobs to update snake grid
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Set up Node.js 20
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Generates a snake game from a GitHub user's contributions graph and outputs an SVG animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: manishsaini0901
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the generated SVG files to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
